### ISSUE TITLE
Used potions are returned upon rejoining

### ISSUE THREAD

**Issue by Wayward1** [Ezhh/warp_potions#2]
I discovered this on Dark Lands Survival. When you use potions to travel using the GUI, the number goes down as expected. But upon leaving the game and rejoining, the missing potions are returned as if they were never used. I have reproduced this several times.

After using: (I started with six each)
![screenshot_20171212_161638](https://user-images.githubusercontent.com/8821916/33908965-0a55c71c-df58-11e7-80f6-e2dd171cd78f.png)

Upon rejoining:
![screenshot_20171212_161658](https://user-images.githubusercontent.com/8821916/33908973-0ed4f90c-df58-11e7-9de0-86c0c352e136.png)

**Comment by Ezhh** [comment]
Thank you for reporting. Will look into it.

**Comment by shivajiva101** [comment]
Added missing inventory state save on potion use and tested. Now works correctly :)

**Comment by Wayward1** [comment]
Sounds good, thank you :)

**Comment by Ezhh** [comment]
Thanks again both - will try get Dark Lands updated with the change over the weekend :)

**Comment by Wayward1** [comment]
No problem, sounds good :)
